name: build and test api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Yadebs.Api/Yadebs.Api.sln
    - name: Build
      run: dotnet build --no-restore Yadebs.Api/Yadebs.Api.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Yadebs.Api/Yadebs.Bll.Tests/Yadebs.Bll.Tests.csproj
    - name: IntegrationTests
      run: dotnet test --no-build --verbosity normal Yadebs.IntegrationTests/Yadebs.IntegrationTests.csproj
